name: Build and deploy GitHub Pages site
on:
  workflow_dispatch:
  push:
    branches: [main]
    paths:
      - ".python-version"
      - "pyproject.toml"
      - "src/**"
      - "uv.lock"

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v7
      - name: Install uv
        uses: astral-sh/setup-uv@v10.0.1
        with:
          enable-cache: true

      - name: Render site
        env:
          GOOGLE_SITE_VERIFICATION_ID: ${{ vars.GOOGLE_SITE_VERIFICATION_ID }}
        run: |
          cd src
          uv run python render_templates.py

      - name: Disable Jekyll
        run: touch build/.nojekyll

      - name: Upload Pages artifact
        uses: actions/upload-pages-artifact@v5
        with:
          path: build

  deploy:
    needs: build
    runs-on: ubuntu-latest

    steps:
      - name: Deploy to GitHub Pages
        uses: actions/deploy-pages@v5
